### PR TITLE
Fix the current position marker that was not center on the map.

### PR DESCRIPTION
**Pull request by resant18**
##Issue Number:

## Description

##Do any new issues need to be created as a result of this PR"?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by khusbuchandra** [comment]
@resant18 , there seems to be some conflict in InitialMap.js related to styling. Could you resolve and check-in again.

**Comment by khusbuchandra** [comment]
@resant18 , could you confirm if your changes are there, Did I resolve it correctly or missed something. if it's all good then I can merge it

**Comment by resant18** [comment]
@khusbuchandra, yes....my changes are there.

**Comment by khusbuchandra** [comment]
Thanks Renata.

**Pull request merged**
