### PR TITLE
Enhancement: Add new feature where user is hovering the place item fr…

### PR DESCRIPTION
**Pull request by resant18**
…om the list, the associated marker is highlighted.

##Issue Number: #133

## Description

##Do any new issues need to be created as a result of this PR"? Yes
- Create a style that highlight a place item box when user hover over it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [X ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.
Created place-hover branch functionality, not including the style.

💔Thank you!

### CODE REVIEW

**Comment by sonalikatara** [comment]
@resant18  there are some merge conflicts , do you want me to resolve it ?

**Comment by resant18** [comment]
@sonalikatara I have time to look at it now. I'll do it.

**Comment by resant18** [comment]
@sonalikatara I've resolved it. Please review it when you have chance, @sonalikatara & @digilou. Thank you!

**Comment by resant18** [comment]
I am not aware of any documentation mentioned about keyboard access to the map, @digilou, but it should be features that we need to include it in the map.

**Pull request merged**
