### PR TITLE
refactoring geolocation.js

### PR DESCRIPTION
**Pull request by sgluzins**
##Issue Number: 
102 

## Description

The Google Maps API has a geocoding service that we can utilize instead of making a separate http request to grab the city/state info we need. Originally, the PR with this code caused an error on first load but that issue is now resolved [https://github.com/gwg-women/gwg-women-techmakers/pull/73].

##Do any new issues need to be created as a result of this PR"?
No

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [X ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by sgluzins** [comment]
@khusbuchandra I am no longer seeing the error on first load. Please let me know if you run into any issues! Thanks :)

**Comment by tanyagupta** [comment]
Hi Sasha
Khusbu is traveling if there are any errors on first load. I can check. I’m not yet near a computer so checking - has the bug fixing PR been merged into dev yet? 
Thanks
Tanya

**Comment by sgluzins** [comment]
hi @tanyagupta! I tagged khusbu since she approved my PR last time. She pointed out an error that she saw and I was able to reproduce. I have fixed those errors so this should be all set now. Right now the code is just on my branch but once the PR is merged it should be in dev! Thanks :)

**Comment by tanyagupta** [comment]
@sgluzins @khusbuchandra does not have access to a computer since she is on holiday.
I will go ahead and merge the PR and to be sure will test it out

**Comment by tanyagupta** [comment]
Hi @sgluzins the sidebar worked for me. I am getting an undefined message at the bottom but I think that is the wiki component and not yours. @sonalikatara can you have a look too ? Thanks @khusbuchandra @agonzalez0515 
capture2

**Comment by PepperAddict** [comment]
hey the description(wiki) relies heavily on header's currentCity and it needs to output it as "city, state" that way wiki can identify that you're referring to a place. I'll take a look too. :)

**Comment by sgluzins** [comment]
@PepperAddict Ahh, good to know! I did have to make some modifications due to having a different repsonse now but i kept the same city, state structure since I had a feeling it was changed that way for a reason which explains that :) Please let me know if you run into any problems or need another set of eyes on it and I will help!

**Comment by sgluzins** [comment]
@tanyagupta thank you for merging and checking it out!

**Comment by PepperAddict** [comment]
Okay, I give up for now. T_T 
 I don't know how to do a state lift correctly. without causing all sorts of problems.
 I need your help @sgluzins or anybody really. I just want to transfer Header.js's  `this.state.currentCity` to App.js that way I can transfer that to Wiki.

**Pull request merged**
