### PR TITLE
bug: remove the sidebar component

### PR DESCRIPTION
**Pull request by sonalikatara**
##Issue Number:
None
## Description

##Do any new issues need to be created as a result of this PR"?
We have the sidebar component in the project that we no more need and I took it out of the project and the import and comment statements that mentioned the sidebar.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Review by sonalikatara — COMMENTED** [review]
Need to remove .DS_Store from here, add it to  .gitignore

**Comment by agonzalez0515** [comment]
Should we also remove other files with this PR?
We don't need `serviceworker-staticmaps.js` and `index-staticmaps.html` anymore.

**Comment by sonalikatara** [comment]
Sure will do that too, don't merge this yet!

**Comment by agonzalez0515** [comment]
Quick tip, if you need to let someone know to not merge your PR yet, you can use `WIP` (work in progress) in the title at the beginning. Not all repos use this convention, but some do. And then when you're work is done, you can change it back to regular title.

**Comment by sonalikatara** [comment]
Thank You for the tip @agonzalez0515 💯

**Review by digilou — APPROVED** [review]

**Review by PepperAddict — APPROVED** [review]
no errors and everything still works great. Thanks for doing the cleaning :D

**Pull request merged**
