### PR TITLE
Added Service Worker

### PR DESCRIPTION
**Pull request by amr08**
Added a new SW to the react project using the cra-append-sw package.  We can now work off sw.js in public.  

Note- after an `npm run build` you will still have to delete React's SW called "service-worker.js".  That's a lot better than me having to copy and paste it in so good job on that package find @agonzalez0515 

##Issue Number: #1 

## Description

Added new sw that will not be ignored in builds.  

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by sonalikatara** [comment]
ouch! Looks like both of us were working on the same feature, I thought I had mentioned it in the discussions yesterday and today. Sorry about the merge request I just made, Please ignore it, saw this a bit late.

**Comment by amr08** [comment]
@sonalikatara Oh I didn't realize :/, sorry about that.  Between the chat, emails, slack, PRs, and issues it's been tough to keep up with all the convos. @tanyagupta @khusbuchandra I think we definitely need to try to move convos back over to issues so we can assign ourselves to avoid doubling up again.

I tried to find your branch to check it out, but it looks like that option is disabled in this repo.  We can't see or fetch each other's branches which makes this a bit more difficult to look at.  

I think we can definitely still use a good amount of your work specially in the sw file itself.  But before diving into that, important question, did you run an npm build to make sure service-worker.js doesn't get replaced by react's?

**Comment by amr08** [comment]
If you try that and it works,  we could try yours and use this PR as a backup since you put a lot of work into.  I wrote very little, my goal was to just to incorporate cra-append-sw in the app to try to solve some of the build problems.

**Comment by sonalikatara** [comment]
cra-append-sw looks like a safer approach, code lines doesn't matter :) I got to learn some skills in the whole process, but I agree we should have one channel of conversation and we need to maybe put in new issues.

**Comment by amr08** [comment]
haha I guess so, but you did some good work here!   It's hard to tell though without being able to run it, but I think if you just copy pasted your `service-worker.js`  into public/sw.js it would still work all the same.

**Pull request merged**
