### PR TITLE
Wrap header with header tag

### LINKED ISSUE #158: Add header tag
Somehow I missed that we didn't have a `header` to wrap the header component. This makes our sections more semantic for accessibility.

### PR DESCRIPTION
**Pull request by digilou**
## Issue Number:
Close #158 

## Description

##Do any new issues need to be created as a result of this PR"?
No.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [X] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by khusbuchandra** [comment]
@digilou , While you are working on header, I have a query. The app  doesn't fit in the screen and overflows with the scroll bar and to see the footer and Wiki i need to scroll. Header takes considerable amount of real estate. I am not great about styles and css so can't point out the technicalities, will share a screenshot hopefully explaining what I see:
image
What i would rather prefer is the complete screen showing up, this is when i reduce zoom of my browser to 50%
image

Is this the case for everyone, or I am the only one seeing this?

P.s: Don't mind about the header data not displaying, must be something in my code or the delay.

**Comment by digilou** [comment]
@khusbuchandra I can easily reduce the padding and font size of the header. Scrolling will still happen in desktop due to the map size and places list, so the height of each would need to be reduced, as well.

Honestly, the scrolling didn't even phase me, but if the expectation is to see the whole thing on desktop, then we definitely need to make a change!

**Comment by sonalikatara** [comment]
@digilou , i agree we should reduce the padding on the header, I also feel there is extra padding above and below the wiki information. There is lot of space between the co-ordinates and the description/info. I will create a new issue for that

**Comment by PepperAddict** [comment]
Looks good to me! I agree a separate issue regarding styles should be created. I have some suggestions as well that I wanted more opinion on.

**Review by PepperAddict — APPROVED** [review]

**Comment by sonalikatara** [comment]
@PepperAddict  @digilou , I am working from a different location today and the padding in wiki info looks good, because unlike my usual location of work, this location has more info and it fits very well in the wiki component. Maybe we need to allign it to the top, so if the info is just a line, it is aligned on top.

what do you say ? 

screen shot 2018-04-03 at 10 04 06 am

**Comment by PepperAddict** [comment]
@sonalikatara what's funny is that that was the exact subject I wanted to bring up. The places sidebar has a set height to avoid it from stretching everything else. 
I don't know how to have it an auto height but contained inside the container(if that makes any sense)
I put my location as new york with its long description and noticed it doesn't look very nice with a long description. I was thinking of having places the same height as the map and then give description the whole column. Let's talk about more style suggestions in an issue I'm going to create.

**Comment by sonalikatara** [comment]
@PepperAddict  let's create a new issue and take this conversation there

**Review by khusbuchandra — APPROVED** [review]
I am approving these changes and we can have another PR for other changes that I requested related to Header, as I don't want PR to stay open for long. Thanks @digilou  for your work.

**Pull request merged**
