### PR TITLE
Cache assets and static map and render them when offline.

### PR DESCRIPTION
**Pull request by agonzalez0515**
## Description
* Cleaned up assets being cached
* Hijack request to static maps and cache the image
* Return static map when MapContainer's props do not load (aka when offline)
* Created a Static Map component

##Do any new issues need to be created as a result of this PR"?
no

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [x] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by khusbuchandra** [comment]
The app should work on those browsers as well which don't have service worker support yet. The check for serviceworker needs to be added in registerServiceWorker.js to avoid below error 
image

**Comment by sonalikatara** [comment]
Angie, got to learn some important caching tricks from your code. Specially the part where you cach the error on fetch of google map api request and return a static map from cache, well playe girl :) 

I have a suggestion that we keep the doCache as it helps in development, I set it to false so that the cache is not being used when I am testing , specially when changing style . What do you think ?

I have seen couple of articles where they suggest we cache style , bundle.js and serviceworker.js 
https://medium.com/zenchef-tech-and-product/service-worker-cache-your-resources-and-other-good-stuff-7642b089fff5

What is your view on this ? I can see why they suggest this ? I think you removed  bundle.js because we have it's root cached so obviously it will be cached too but are the styles being cached ?  

Everything looks good to go otherwise.

**Comment by sonalikatara** [comment]
It works !!
I suggest we keep one google api key so get rid of REACT_APP_STATICMAP in staticMap.js and use the current REACT_APP_GKEY
I just put the same key for both as I had static maps api added to the key we have been using for other api calla using.

**Comment by agonzalez0515** [comment]
Regarding the assets, we're caching the ones created by the build command. So webpack bundles all styles and all js into those two files `static/css` and `static/js`. We don't have a `src/styles` path in our project. As far as I can tell, please correct me if I'm wrong, we don't need to cache that because it doesn't lead to anything.

**Comment by agonzalez0515** [comment]
ToDo before merge:
- [ ] Fix conflict
- [ ] Add service woker detection so that it does't fail on non-supported browsers
- [ ] Use 1 Google Api key

**Comment by sonalikatara** [comment]
@agonzalez0515 it's in sw.js line 49 , i am looking at the file changed tab above, if you don't see it, let me know and i can add it in my next pr as it is not a big issue

**Comment by agonzalez0515** [comment]
Updated pull request! @khusbuchandra Can you please check edge browser?

**Comment by khusbuchandra** [comment]
Mappa works now for Edge. Good work @agonzalez0515 
image

**Pull request merged**
