### PR TITLE
Added a button to recenter the map to user's current position

### PR DESCRIPTION
**Pull request by sonalikatara**
##Issue Number:
  #162 and  #168 

## Description

Added a button to recenter the map to user's current position,
Added a new state to the App for storing the user position
Removed Milligram from package.json and App.js as I had to work on the button styles
Got rid of the placeholder image from infoWindow

##Do any new issues need to be created as a result of this PR"?
No

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ x] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by PepperAddict** [comment]
hey I just ran it. I got this error in the console:

index.js:2178 Warning: React does not recognize the `mapCenter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mapcenter` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (at InitialMap.js:175)
    in div (created by Map)
    in Map (at InitialMap.js:166)
    in div (at InitialMap.js:164)
    in div (at InitialMap.js:162)
    in MapContainer (created by Wrapper)
    in div (created by Wrapper)
    in Wrapper (at App.js:100)
    in div (at App.js:99)
    in main (at App.js:94)
    in div (at App.js:86)
    in App (at index.js:7)

But everything seemed to run fine and the button works beautifully.

**Comment by sonalikatara** [comment]
Thank you for reviewing @pepper. Yes I am getting this warning if I put the
button in the MapComponent. If I keep it out I don’t get the error, but the
button doesn’t overlay on the map. I should suggest creating a new issue
for this and look into it.

**Review by PepperAddict — APPROVED** [review]
aside from the error, everything works great. 
We'll have to try and figure out that error later.

**Comment by digilou** [comment]
@sonalikatara @PepperAddict Can we overlay appearance using CSS grid?

**Review by digilou — COMMENTED** [review]
@sonalikatara @PepperAddict Can we overlay appearance using CSS grid?

**Review by digilou — CHANGES_REQUESTED** [review]
Also, can you move the styling to the stylesheet as `#btnRecenter{}`? Styling would be more manageable that way. I'll test your branch when I get home tonight to see if there's any noticeable accessibility issues.

**Comment by sonalikatara** [comment]
Amy I tried putting it above the div containing map and set position to
relative and set the z-index but the map was rendered over the button, any
suggestions?

**Comment by sonalikatara** [comment]
I can do that but in css, I don’t have a sass compiler, do you want me to
put it in index.css and you take care of putting it in sass file. That
would be great.

**Comment by sonalikatara** [comment]
Hi All, I noticed the button is getting a mapCenter property which is
conflicting with React’s api. I will investigate and send a Pr again. I am
not at my laptop for few hours so will do it later tonight. Sorry about
this.

**Comment by digilou** [comment]
@sonalikatara Which text editor do you use? In VS Code I installed a plugin and set up a task to transpile the SCSS to CSS: https://code.visualstudio.com/Docs/languages/CSS
Not sure how @PepperAddict has been doing hers.

**Comment by sonalikatara** [comment]
@pepper uses vscode too but I use sublimeText. There is a package i can
download and use, but I will need sometime to configure all that.

**Review by digilou — APPROVED** [review]

**Comment by digilou** [comment]
@sonalikatara I can create an issue to move the code over. Don't worry about configuring your setup. I know how overwhelming all the little things put together can be. Thanks for tackling this!

**Pull request merged**
