### PR TITLE
Fixed for different array lengths

### PR DESCRIPTION
**Pull request by PepperAddict**
##Issue Number:  #170 

## Description

- minor edit > App.js  - We don't need the city[0] city[1] anymore since that was handled in geolocation.js 
- big edit > Geolocation.js  -  It just needed more if statements to handle different situations. 
- minor edit >  Description.js - Instead of picking the 2nd array element as the country fallback, it'll pick the last array element just in case there is more than 2 elements in the array.

##Do any new issues need to be created as a result of this PR"?
After a bunch of testing I do not think there was any trouble caused by this. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [x] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

### CODE REVIEW

**Comment by sgluzins** [comment]
hi @PepperAddict! How did you test this with other locations? I set the geolocation to something different in dev tools -> sensors -> geolocation which updates and shows the map/places with the new location but it won't load the description or header. I added some console logs and those don't even show up. Any thoughts?? When it defaults to my actual geolocation, all 4 items load (map, header, description, places).

**Comment by PepperAddict** [comment]
hi @sgluzins I never figured out sensors but this one worked for me: 
https://chrome.google.com/webstore/detail/manual-geolocation/jpiefjlgcjmciajdcinaejedejjfjgki?hl=en

**Comment by sgluzins** [comment]
@PepperAddict thanks!! After installing that plugin I had the same results. Figured out what I was doing wrong - I had to set the location beforehand. I was able to test out a bunch of scenarios (google chrome has a few default locations that you can pick in sensors).

I'm not sure how we would approach how Mumbai is showing up but San Paulo looks like an extra error scenario we might want to add? Here are some screenshots that include the lat/lng and results (I added some console logs locally for testing purposes):

screen shot 2018-04-08 at 8 01 30 pm

screen shot 2018-04-08 at 8 03 05 pm


Looks great though! A bunch of the locations I tested loaded as expected :)

**Review by sgluzins — CHANGES_REQUESTED** [review]
I think we want to consider adding additional scenarios or think about how to handle situations similar to Mumbai / San Paulo (comment includes screenshots).

I'm okay if we merge this though and consider it as an enhancement since they seem more like edge cases??

**Comment by PepperAddict** [comment]
thank you for helping me test. i will dig more into this tomorrow.

**Comment by PepperAddict** [comment]
I think my approach was wrong working from start to end. I think working from end to start is better. That way it ignores all the unnecessary entries from some countries. 

Hope this one's better.

**Comment by sgluzins** [comment]
sweet! I re-tested those countries and some other locations and it looks good! :) I tested my home location and of course, it decided it doesn't want to cooperate with the new changes -___-  I think it just needs an update to the regex though based on what I was seeing: 

I'm in Pasadena, CA and it is showing "N El Molino Ave, Pasadena, CA" which is one of the streets surrounding me. I put a console log before and after "city = city.replace(/\b\w*?Unnamed Road|-|USA|[a-z]*\d+[a-z]*\w*?\b/gi, '');" (~line 23 in geolocation.js) and these were the results:

before = 53 N El Molino Ave, Pasadena, CA 91101, USA
after = N El Molino Ave, Pasadena, CA , 

so it looks like its only shaving off the "53" instead of the whole street "53 N El Molino Ave" in the regex. Let me know if you want me to test some regex options on my end to see if they work out for me where I am located - happy to help if that makes it easier!

**Comment by PepperAddict** [comment]
Hey! Thanks again for helping me test. I was having a bit of a dilemma. I wanted other places to show 
Montreal, QC, Canada
But now there's the problem of USA. 
For the regex I removed -, USA, numbers with their words, Unnamed Road, and I think there were others...
I think I have an idea. Those with 3 elements should only show the last 2 . Hmmm...  USA is priority so I'm going to work towards making USA look good.

**Comment by PepperAddict** [comment]
What works: 
- Okay, I think I fixed that problem. USA and their zip code has been removed so now they're down to only 3 elements with regex. street address, city, state. With the if statement, now it only shows city, state in header and description.  I did a bunch of testing and I haven't found one with more than 3 elements so I'm pretty sure this worked.
- Countries look fine. Even if they had 3 or less elements, there wouldn't be any confusion since it'll show their city and country.

what doesn't work: 
- You know how states have the acronym CT for connecticut and so on. Unfortunately so does Canada. Most of Canada actually have 4 elements so it actually shows Montreal, QC, Canada.  But unfortunately for a minor few it has 3 elements and since I created an if statement for 3 elements to only show the last two elements, it ended up showing up as SK, Canada.  Which can be a bit mehh...

If you liked the street address part, I think we may need to rethink how to do this. I decided to get rid of numbers along with the word in regex because some countries had weird numbers and words along with its name. 
Like N32 London   or something like that which was a huge problem for the wiki and also because it was tacky.

I think I finally got it, but please let me know if there are more problems (other than poor Canada). 
I'm contemplating on writing a function that looks for acronyms and then turning it into their actual name.

**Comment by PepperAddict** [comment]
I added full state name to replace abbreviations because. 
1. It helps out the wiki just a little bit. Like for example I got just 1 array element for Oregan but the abbreviated version doesn't work too well with wiki. You'll end up getting "OR may refer to...."
2. it helps with places like in Canada where it shows SK, Canada when it would look better as: Saskatchewan, Canada

Do you think I should add Canada to regex remove? 
That way it would look like this: 
Leroy, Saskatchewan 

edit:
Ummm.. i went ahead and put Canada and Mexico in the regex removal to show their city and state instead. I even added Mexico states abbr to their full name list in the state object list.

**Comment by sonalikatara** [comment]
@PepperAddict @sgluzins  is this PR ready for review, or are we still working on it ?

**Review by digilou — APPROVED** [review]
I'm okay with merging to see what else comes up. You've put more thought into than I have! Is there any way to write tests for this to help us get a clearer idea on other "edge" cases?

**Review by sgluzins — APPROVED** [review]
I agree with @digilou! I did test the countries again and my home location and everything looks good :) Thanks @PepperAddict for all your thoughts on this!!

**Comment by PepperAddict** [comment]
Thank you ladies!
@digilou This is what we used to check different locations: Manual Geolocation chrome addon
https://chrome.google.com/webstore/detail/manual-geolocation/jpiefjlgcjmciajdcinaejedejjfjgki?hl=en

There's a chrome sensor way but I never figured that out D:

**Pull request merged**
